//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusStory.База_данных
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BaseModelFocusEntities5 : DbContext
    {
        private static BaseModelFocusEntities5 _context;

        public BaseModelFocusEntities5()
            : base("name=BaseModelFocusEntities5")
        {
        }

        public static BaseModelFocusEntities5 GetContext()
        {
            if (_context == null)
                _context = new BaseModelFocusEntities5();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
