//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusStory.База_данных
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int idBasket { get; set; }
        public Nullable<int> idItem { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
